version: '3.8'

services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securecapita
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - securecapita_net

  backend:
    image: anikondu87/securecapita-backend:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/securecapita
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - securecapita_net

  frontend:
    image: anikondu87/securecapita-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - securecapita_net

volumes:
  mariadb_data:

networks:
  securecapita_net:
    driver: overlay
