version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080 #Management UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securecapita
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - securecapita_net
    labels:
      - "traefik.http.routers.db.rule=Host(`db.coran-hadith.fr`)"
      - "traefik.http.services.db.loadbalancer.server.port=3306"

  backend:
    image: anikondu87/securecapita-backend:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/securecapita
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - securecapita_net
    labels:
      - "traefik.http.routers.api.rule=Host(`api.coran-hadith.fr`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  frontend:
    image: anikondu87/securecapita-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - securecapita_net
    labels:
      - "traefik.http.routers.ui.rule=Host(`coran-hadith.fr`)"
      - "traefik.http.services.ui.loadbalancer.server.port=80"

volumes:
  mariadb_data:

networks:
  securecapita_net:
    driver: bridge
