version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=reda.berkouch@live.fr
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 4321:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - securecapita_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securecapita
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dbadmin.rule=Host(`admin.coran-hadith.fr`)"
        - "traefik.http.routers.dbadmin.entrypoints=websecure"
        - "traefik.http.routers.dbadmin.tls.certresolver=myresolver"
        - "traefik.http.services.dbadmin.loadbalancer.server.port=80"

  backend:
    image: anikondu87/securecapita-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/securecapita
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`api.coran-hadith.fr`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=myresolver"
        - "traefik.http.services.api.loadbalancer.server.port=8080"

  frontend:
    image: anikondu87/securecapita-frontend:latest
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ui.rule=Host(`coran-hadith.fr`)"
        - "traefik.http.routers.ui.entrypoints=websecure"
        - "traefik.http.routers.ui.tls.certresolver=myresolver"
        - "traefik.http.services.ui.loadbalancer.server.port=80"

  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ROOT_URL=https://chat.coran-hadith.fr
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chat.rule=Host(`chat.coran-hadith.fr`)"
        - "traefik.http.routers.chat.entrypoints=websecure"
        - "traefik.http.routers.chat.tls.certresolver=myresolver"
        - "traefik.http.services.chat.loadbalancer.server.port=3000"

  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  mariadb_data:
  letsencrypt:
  mongo_data:

networks:
  securecapita_net:
    driver: overlay
