version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=reda.berkouch@live.fr
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 4321:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - securecapita_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securecapita
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dbadmin.rule=Host(`admin.coran-hadith.fr`)"
        - "traefik.http.routers.dbadmin.entrypoints=websecure"
        - "traefik.http.routers.dbadmin.tls.certresolver=myresolver"
        - "traefik.http.services.dbadmin.loadbalancer.server.port=80"

  backend:
    image: anikondu87/securecapita-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/securecapita
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`api.coran-hadith.fr`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=myresolver"
        - "traefik.http.services.api.loadbalancer.server.port=8080"

  frontend:
    image: anikondu87/securecapita-frontend:latest
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ui.rule=Host(`coran-hadith.fr`)"
        - "traefik.http.routers.ui.entrypoints=websecure"
        - "traefik.http.routers.ui.tls.certresolver=myresolver"
        - "traefik.http.services.ui.loadbalancer.server.port=80"

  jitsi-prosody:
    image: jitsi/prosody:stable
    environment:
      - XMPP_DOMAIN=meet.coran-hadith.fr
      - XMPP_AUTH_DOMAIN=auth.meet.coran-hadith.fr
      - XMPP_MUC_DOMAIN=muc.meet.coran-hadith.fr
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.coran-hadith.fr
      - JICOFO_COMPONENT_SECRET=s3cr3t
      - JICOFO_AUTH_PASSWORD=s3cr3t
      - JVB_AUTH_PASSWORD=s3cr3t
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  jitsi-web:
    image: jitsi/web:stable
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - XMPP_DOMAIN=meet.coran-hadith.fr
      - XMPP_BOSH_URL_BASE=http://jitsi-prosody:5280
      - XMPP_SERVER=jitsi-prosody
      - PUBLIC_URL=https://meet.coran-hadith.fr
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jitsi.rule=Host(`meet.coran-hadith.fr`)"
        - "traefik.http.routers.jitsi.entrypoints=websecure"
        - "traefik.http.routers.jitsi.tls.certresolver=myresolver"
        - "traefik.http.services.jitsi.loadbalancer.server.port=80"

  jitsi-jicofo:
    image: jitsi/jicofo:stable
    environment:
      - XMPP_DOMAIN=meet.coran-hadith.fr
      - XMPP_AUTH_DOMAIN=auth.meet.coran-hadith.fr
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.coran-hadith.fr
      - JICOFO_COMPONENT_SECRET=s3cr3t
      - JICOFO_AUTH_PASSWORD=s3cr3t
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  jitsi-jvb:
    image: jitsi/jvb:stable
    environment:
      - XMPP_AUTH_PASSWORD=s3cr3t
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.coran-hadith.fr
      - DOCKER_HOST_ADDRESS=127.0.0.1
    networks:
      - securecapita_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  mariadb_data:
  letsencrypt:

networks:
  securecapita_net:
    driver: overlay
