services:

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securecapita
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - securecapita_net

  backend:
    image: anikondu87/securecapita-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/securecapita
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"  # Expose le backend à l'extérieur (utile pour tests direct)
    networks:
      - securecapita_net
      - traefik_net

  frontend:
    image: anikondu87/securecapita-frontend:latest
    ports:
      - "80:80"  # Expose le frontend sur le port HTTP standard
    networks:
      - securecapita_net
      - traefik_net

volumes:
  mariadb_data:

networks:
  securecapita_net:
  traefik_net:
