version: '3.8'

services:

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securecapita
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - securecapita_net

  backend:
    image: anikondu87/securecapita-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/securecapita
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    expose:
      - "8080"  # Permet à Traefik de voir le port
    networks:
      - securecapita_net
      - traefik_net

  frontend:
    image: anikondu87/securecapita-frontend:latest
    expose:
      - "80"
    networks:
      - securecapita_net
      - traefik_net

volumes:
  mariadb_data:

networks:
  securecapita_net:
    external: true
  traefik_net:
    external: true
