version: '3.8'

services:

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8080"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=reda.berkouch@live.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # externe:interne pour accéder au dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/letsencrypt:/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik_net


  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securecapita
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - securecapita_net

  backend:
    image: anikondu87/securecapita-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/securecapita
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    deploy:
      labels:
      - "traefik.enable=false"
    networks:
      - securecapita_net
      - traefik_net

  frontend:
    image: anikondu87/securecapita-frontend:latest
    deploy:
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.frontend.rule=Host(`coran-hadith.fr`, `www.coran-hadith.fr`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=myresolver"
        - "traefik.http.routers.frontend.middlewares=redirect-to-https,redirect-to-non-www"

        - "traefik.http.routers.frontend-http.entrypoints=web"
        - "traefik.http.routers.frontend-http.rule=Host(`coran-hadith.fr`, `www.coran-hadith.fr`)"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

        - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https://www\\.(.*)"
        - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$$1"
    networks:
      - securecapita_net
      - traefik_net

volumes:
  mariadb_data:

networks:
  securecapita_net:
    external: true
  traefik_net:
    external: true
