version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securecapita
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: securecapita-backend
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/securecapita
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build:
      context: ./frontend
    container_name: securecapita-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mariadb_data:
